export EDITOR='vim'
export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::" )
alias l="ls -lahF"
alias ll="ls -lhF"
alias lc="locale"
alias utog="iconv -futf8 -tgbk"
alias gtou="iconv -fgbk -tutf8"
alias ..="cd .."
alias ...="cd ../.."
