export EDITOR='vim'
export JAVA_HOME=$(/usr/libexec/java_home)
alias l="ls -lahF"
alias ll="ls -lhF"
alias lc="locale"
alias utog="iconv -futf8 -tgbk"
alias gtou="iconv -fgbk -tutf8"
alias ..="cd .."
alias ...="cd ../.."
